### ISSUE TITLE
test failures in 2.3.2

### ISSUE THREAD

**Issue by alunduil** [lepture/python-livereload#102]
These tests are failing in the 2.3.2 release under python-3.3:

```
======================================================================
FAIL: tests.test_watcher.TestWatcher.test_watch_dir
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/var/tmp/portage/dev-python/livereload-2.3.2/work/livereload-2.3.2/tests/test_watcher.py", line 31, in test_watch_dir
    assert watcher.is_changed(tmpdir)
AssertionError

======================================================================
FAIL: tests.test_watcher.TestWatcher.test_watch_file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/var/tmp/portage/dev-python/livereload-2.3.2/work/livereload-2.3.2/tests/test_watcher.py", line 46, in test_watch_file
    assert watcher.is_changed(filepath)
AssertionError

======================================================================
FAIL: tests.test_watcher.TestWatcher.test_watch_glob
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/var/tmp/portage/dev-python/livereload-2.3.2/work/livereload-2.3.2/tests/test_watcher.py", line 60, in test_watch_glob
    assert watcher.examine() is None
AssertionError
```

Are these failures anything to be concerned about or are they ignorable?  If they are of concern I can attempt a patch; otherwise, I'll simply ignore these tests.

**Comment by alunduil** [comment]
Looks like new files being added to a directory isn't handled correctly by the built-in Watcher.  At least for the first test.

**Comment by alunduil** [comment]
The second test appears to break due to watch not setting an initial mtime on files.  The test also assumes that it knows if a file changed before it's started watching that file. Which won't be true due to mtime tracking.

**Comment by alunduil** [comment]
The third test assumes examine returns ``None`` but it returns a tuple, ``(None, None, )`` or a popped item from _changes (if _changes has items).  During the first assert in the third test the former should be true but is not.

**Comment by alunduil** [comment]
If you have any guidance on how you'd like these issues solved, I'd be happy to take a crack at writing a patch.

**Comment by lepture** [comment]
Just fixed test cases.
