### ISSUE TITLE
Failure with current master

### ISSUE THREAD

**Issue by d0ugal** [lepture/python-livereload#107]
I get this with the current git master. It works with `2.3.2`.

We may be doing something wrong, I'm not sure. Our code to replicate this can be found here:
https://github.com/mkdocs/mkdocs/blob/master/mkdocs/serve.py#L11-L26

```
INFO    -  Building documentation... 
Traceback (most recent call last):
  File "./.tox/livereload-dev/bin/mkdocs", line 9, in <module>
    load_entry_point('mkdocs==0.13.0.dev0', 'console_scripts', 'mkdocs')()
  File "/home/dougalmatthews/Code/python/mkdocs/.tox/livereload-dev/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/dougalmatthews/Code/python/mkdocs/.tox/livereload-dev/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/dougalmatthews/Code/python/mkdocs/.tox/livereload-dev/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dougalmatthews/Code/python/mkdocs/.tox/livereload-dev/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dougalmatthews/Code/python/mkdocs/.tox/livereload-dev/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/dougalmatthews/Code/python/mkdocs/.tox/livereload-dev/lib/python2.7/site-packages/mkdocs/cli.py", line 75, in serve_command
    livereload=livereload,
  File "/home/dougalmatthews/Code/python/mkdocs/.tox/livereload-dev/lib/python2.7/site-packages/mkdocs/serve.py", line 83, in serve
    _livereload(host, port, config, builder, tempdir)
  File "/home/dougalmatthews/Code/python/mkdocs/.tox/livereload-dev/lib/python2.7/site-packages/mkdocs/serve.py", line 20, in _livereload
    server.watch(config['docs_dir'], builder)
  File "/home/dougalmatthews/Code/python/mkdocs/.tox/livereload-dev/lib/python2.7/site-packages/livereload/server.py", line 198, in watch
    self.watcher.watch(filepath, func, delay)
TypeError: unbound method watch() must be called with Watcher instance as first argument (got str instance instead)
```

To replicate this locally with Tox, you need the small additions I made here to the tox config here: https://github.com/d0ugal/mkdocs/tree/tox-additions then run:

    tox -e livereload-dev
    ./.tox/livereload-dev/bin/mkdocs serve

That should start serving the MkDocs documentation on locahost:8000. To compare with a working version run:

    tox -e py34-unittests
    ./.tox/py34-unittests/bin/mkdocs serve

**Comment by lepture** [comment]
@d0ugal This is a very silly bug.

**Comment by d0ugal** [comment]
Updated and got this instead:

```
INFO    -  Building documentation... 
Serving on http://127.0.0.1:8000
ERROR:tornado.application:Uncaught exception GET /livereload.js (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/livereload.js', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-GB,en-US;q=0.8,en;q=0.6', 'Accept-Encoding': 'gzip, deflate, sdch', 'Referer': 'http://localhost:8000/', 'Host': '127.0.0.1:8000', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36'})
Traceback (most recent call last):
  File "/home/dougalmatthews/Code/python/mkdocs/.tox/livereload-dev/lib/python2.7/site-packages/tornado/web.py", line 1346, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/dougalmatthews/Code/python/mkdocs/.tox/livereload-dev/lib/python2.7/site-packages/livereload/handlers.py", line 128, in get
    self.write(resource_string(__name__, 'vendors/livereload.js'))
  File "/home/dougalmatthews/Code/python/mkdocs/.tox/livereload-dev/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1161, in resource_string
    self, resource_name
  File "/home/dougalmatthews/Code/python/mkdocs/.tox/livereload-dev/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1589, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/home/dougalmatthews/Code/python/mkdocs/.tox/livereload-dev/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1712, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 2] No such file or directory: '/home/dougalmatthews/Code/python/mkdocs/.tox/livereload-dev/lib/python2.7/site-packages/livereload/vendors/livereload.js'
ERROR:tornado.access:500 GET /livereload.js (127.0.0.1) 2.48ms
```

**Comment by d0ugal** [comment]
This looks like it is because the manifest has the wrong location for livereload.js.

**Comment by lepture** [comment]
Yes. I've changed the location of livereload.js.

**Comment by lepture** [comment]
updated with https://github.com/lepture/python-livereload/commit/823307d8111158d90bfe67ae873cbb4b7dae23ca

**Comment by d0ugal** [comment]
Great, everything appears to work with the MkDocs use case now. I'll test over the next few days.
