### ISSUE TITLE
[critical bug] crashes when monitoring directory contains unicode

### ISSUE THREAD

**Issue by CaledoniaProject** [lepture/python-livereload#138]
I got an error like this,

```
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 1346, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Library/Python/2.7/site-packages/livereload/handlers.py", line 174, in get
        filepath = self.filepath(path)
      File "/Library/Python/2.7/site-packages/livereload/handlers.py", line 162, in filepath
        url = os.path.join(self._root, url)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 73, in join
        path += '/' + b
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 41: ordinal not in range(128)
```

**Comment by CaledoniaProject** [comment]
To reproduce the bug, use `ceshi测试` as directory name
