### ISSUE TITLE
ImportError: No module named management.commands.livereload

### ISSUE THREAD

**Issue by sanatankumar** [lepture/python-livereload#151]
I  have already installed livereload and added in settings.py in my  django application as per as documentation but for some reason running `./manage.py livereload` is giving me Import Error

**Comment by awkwardengineer** [comment]
I'm having the same thing. did you ever find a fix?

**Comment by lepture** [comment]
What version are you using? Have you ever tried the code in master branch?

**Comment by awkwardengineer** [comment]
Python 2.7, and I'm pretty sure I have the brand new python-reload 2.0

**Comment by awkwardengineer** [comment]
here's the trace

```
Running ENVIRONMENT  DEV
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/sam/wgportal/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/sam/wgportal/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sam/wgportal/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 205, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/sam/wgportal/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named management.commands.livereload

```

**Comment by RonnyPfannschmidt** [comment]
setup.py has a bug wrt not listing all package namespaces 

so it works on python3 due to implied namespaces and fails to have the module on python2

a workaround is a editable install

i strongly suggest a switch to setuptools find_packages
