### ISSUE TITLE
livereload in docker container not working

### ISSUE THREAD

**Issue by caphrim007** [lepture/python-livereload#174]
Hello,

I have a livereload running in a docker container hosting some sphinx documentation that I built. I am trying to use it to to navigate the docs while I edit them outside of the container. I attempt to start `livereload` like so

```
 livereload --host 0.0.0.0 -p 8000 docs/_build/html/
```

From inside the container, and that works fine. However, when I surf to the page to view the docs, I get the following error.

```
[I 180703 22:16:15 server:292] Serving on http://0.0.0.0:8000
[I 180703 22:16:15 handlers:59] Start watching changes
[I 180703 22:16:15 handlers:61] Start detecting changes
[E 180703 22:16:17 web:1621] Uncaught exception GET /userguide/about-as3.html (172.17.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8000', method='GET', uri='/userguide/about-as3.html', version='HTTP/1.1', remote_ip='172.17.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 260, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 315, in wrapper
        yielded = next(result)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2472, in get
        yield self.flush()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 973, in flush
        start_line, self._headers, chunk, callback=callback)
      File "/usr/local/lib/python2.7/dist-packages/tornado/http1connection.py", line 403, in write_headers
        data += self._format_chunk(chunk)
      File "/usr/local/lib/python2.7/dist-packages/tornado/http1connection.py", line 415, in _format_chunk
        "Tried to write more data than Content-Length")
    HTTPOutputError: Tried to write more data than Content-Length
[E 180703 22:16:17 web:1042] Cannot send error response after headers written
```

It appears the -148 bytes are being detected by tornado...for reasons unknown...but the headers are the following

```
 0.0s write_headers: k='Connection', v='Upgrade'
 0.0s write_headers: k='Date', v='Tue, 03 Jul 2018 21:53:40 GMT'
 0.0s write_headers: k='Sec-Websocket-Accept', v='rhbSxvq2M8ltJL2dQgWpQ+zNv2o='
 0.0s write_headers: k='Server', v='TornadoServer/5.0.2'
 0.0s write_headers: k='Upgrade', v='websocket'
```

If I downgrade tornado to any version < 4, the error goes away.

I'm scratching my head as to what the problem might be though, because I see release notes for `livereload` that say its fixing stuff in tornado 4.5+

Any ideas?

Thanks!

**Comment by schnitzelbub** [comment]
@caphrim007 I experience the same behavior without Docker using [sphinx-autobuild](https://github.com/GaretJax/sphinx-autobuild). In my case it only occurs when serving static local MathJax file `extensions/MathMenu.js` ([cf. similar issue](https://github.com/mkdocs/mkdocs/issues/1351))!?
I was trying to find the spot where it originates, but got lost in the unknown tornado code.

Any ideas how to resolve this?

**Comment by pradyunsg** [comment]
The issue here is the `</head>` in MathMenu.js triggering a bit of logic that should not be getting triggered when serving Javascript files.

See https://github.com/GaretJax/sphinx-autobuild/issues/71#issuecomment-681854580 for more analysis.

**Comment by pradyunsg** [comment]
Here's the change that needs to be made upstream (i.e. in this project) to fix this issue.

https://github.com/executablebooks/sphinx-autobuild/pull/91/files#diff-880bbd48378ec08ac1af7d30ee85b96aR20-R24

**Comment by pradyunsg** [comment]
PRs welcome to fix this. :)
