### ISSUE TITLE
RuntimeError: Cannot close a running event loop

### ISSUE THREAD

**Issue by guomaoqiu** [lepture/python-livereload#176]
**- Error:**
    Traceback (most recent call last):
      File "/Users/Green/py36/lib/python3.6/site-packages/tornado/ioloop.py", line 1229, in _run
        return self.callback()
      File "/Users/Green/py36/lib/python3.6/site-packages/tornado/autoreload.py", line 185, in _reload_on_update
        _check_file(modify_times, path)
      File "/Users/Green/py36/lib/python3.6/site-packages/tornado/autoreload.py", line 200, in _check_file
        _reload()
      File "/Users/Green/py36/lib/python3.6/site-packages/tornado/autoreload.py", line 207, in _reload
        fn()
      File "/Users/Green/py36/lib/python3.6/site-packages/livereload/server.py", line 310, in <lambda>
        add_reload_hook(lambda: IOLoop.instance().close(all_fds=True))
      File "/Users/Green/py36/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 71, in close
        self.asyncio_loop.close()
      File "/Users/Green/.pyenv/versions/3.6.0/lib/python3.6/asyncio/unix_events.py", line 63, in close
        super().close()
      File "/Users/Green/.pyenv/versions/3.6.0/lib/python3.6/asyncio/selector_events.py", line 107, in close
        raise RuntimeError("Cannot close a running event loop")
    RuntimeError: Cannot close a running event loop

**- Run ENV:**
 python 3.6 
 livereload: 2.5.2

**my flask app manager settings:**

@manager.command
def dev():
    live_server = Server(app.wsgi_app)
    live_server.watch('**/**')
    live_server.serve(open_url=False,port=5000,debug=True)

When I press ctrl+c to save the file, terminal reports an error.
My app is running as ：
~/py36/bin/python manager.py dev

# please help me  thanks.

**Comment by cmbasnett** [comment]
You may need to downgrade to 2.5.1: https://github.com/lepture/python-livereload/issues/170

**Comment by kariavka** [comment]
@cmbasnett ❤❤❤

**Comment by d1618033** [comment]
Happens for me too. 

It seems that in tornado [they decided to remove the ioloop.close](https://github.com/tornadoweb/tornado/pull/1984) because it's unneeded in python 3.4+.
A few months later, the ioloop.close was [added to python-livereload](https://github.com/lepture/python-livereload/commit/77a40ad0df87a7b88c483848115a7d6a372ea93d). This is what caused the aforementioned bug to occur.

**Comment by EpicCodeWizard** [comment]
Versions 2.5.2+ have this issue. Downgrade to version 2.5.1 (```pip install livereload==2.5.1```).

**Comment by rpaladin** [comment]
I downgraded to `2.5.1` as suggested, but then I get the error mentioned in #209.

What is the proposed solution if we're not allowed to use later versions and past versions are broken or incompatible?
