### ISSUE TITLE
[E 210111 16:54:46 ioloop:907] Exception in callback functools.partial?

### ISSUE THREAD

**Issue by weijen6** [lepture/python-livereload#241]
Python 3.8.9
Flask 1.1.1
python-livereload 2.6.3
Win10 20H2
VSCODE 1.52.1

my code
`
from flask import Flask, render_template
from livereload import Server
app = Flask(__name__)
app.config['DEBUG'] = True
app.config['TEMPLATES_AUTO_RELOAD'] = True
app.config['SEND_FILE_MAX_AGE_DEFAULT'] = 0

@app.route('/')
def about_page():
    return '<h2>about</h2>'
    
if __name__ == '__main__':
    server = Server(app.wsgi_app)
    server.serve(port=5000)
`

When I modify the return value and press ctrl + s, the following error will appear

PS D:\Flask> & C:/Users/weijen/AppData/Local/Programs/Python/Python38/python.exe d:/Flask/app.py
[I 210111 16:54:31 server:335] Serving on http://127.0.0.1:5000
[I 210111 16:54:31 handlers:58] Watch current working directory
[I 210111 16:54:31 handlers:62] Start watching changes
[I 210111 16:54:31 handlers:64] Start detecting changes
[E 210111 16:54:46 ioloop:907] Exception in callback functools.partial(<function _reload_on_update at 0x0000022BBC07E040>
    {'C:\\Users\\weijen\\AppData\\Local\\Programs\\Python\\Python38\\lib\\importlib\\_bootstrap.py': 1595232212.0,
    ............
   .............
    'C:\\Users\\weijen\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\livereload\\__init__.py': 1610291954.9496043, 'C:\\Users\\weijen\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tornado\\platform\\__init__.py': 1604266804.291237, 'C:\\Users\\weijen\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tornado\\platform\\asyncio.py': 1604266804.2922547})
    Traceback (most recent call last):
      File "C:\Users\weijen\AppData\Local\Programs\Python\Python38\lib\site-packages\tornado\ioloop.py", line 905, in _run
        return self.callback()
      File "C:\Users\weijen\AppData\Local\Programs\Python\Python38\lib\site-packages\tornado\autoreload.py", line 187, in _reload_on_update
        _check_file(modify_times, path)
      File "C:\Users\weijen\AppData\Local\Programs\Python\Python38\lib\site-packages\tornado\autoreload.py", line 202, in _check_file
        _reload()
      File "C:\Users\weijen\AppData\Local\Programs\Python\Python38\lib\site-packages\tornado\autoreload.py", line 209, in _reload
        fn()
      File "C:\Users\weijen\AppData\Local\Programs\Python\Python38\lib\site-packages\livereload\server.py", line 355, in <lambda>
        add_reload_hook(lambda: IOLoop.instance().close(all_fds=True))
      File "C:\Users\weijen\AppData\Local\Programs\Python\Python38\lib\site-packages\tornado\platform\asyncio.py", line 
140, in close
        self.asyncio_loop.close()
        raise RuntimeError("Cannot close a running event loop")
    RuntimeError: Cannot close a running event loop
[I 210111 16:56:26 server:358] Shutting down...

**Comment by HB6H057** [comment]
You may need to downgrade to 2.5.1

**Comment by EpicCodeWizard** [comment]
Versions 2.5.2+ have this issue. Downgrade to version 2.5.1 (```pip install livereload==2.5.1```).
