### ISSUE TITLE
livereload.js can't be found after bundling with pyinstaller 

### ISSUE THREAD

**Issue by OleMussmann** [lepture/python-livereload#257]
After bundling (pyinstaller) a script that makes use of livereload, the file livereload.js can't be found when opening the website in a browser. Without bundling the script works fine though. Is that an issue with livereload or pyinstaller?

For context: The script and it's dependencies live in a pipenv.

```
[E 220429 17:47:53 web:1789] Uncaught exception GET /livereload.js?port=8000 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/livereload.js?port=8000', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "tornado/web.py", line 1702, in _execute
      File "livereload/handlers.py", line 219, in get
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIlQVXGm/livereload/vendors/livereload.js'
[E 220429 17:47:53 web:2239] 500 GET /livereload.js?port=8000 (127.0.0.1) 0.96ms
```

**Comment by OleMussmann** [comment]
Note for future self (or you who probably stumbled upon this via google). Fixed by adding the file `livereload/vendors/livereload.js` into the bundle. For `pyinstaller` this works via

    pyinstaller --add-data livereload/vendors/livereload.js:livereload/vendors/ my_script.py

or with `nuitka`

    python3 -m nuitka --include-data-file=livereload/vendors/livereload.js=livereload/vendors/livereload.js my_script.py
