### ISSUE TITLE
doesn't start in venv

### ISSUE THREAD

**Issue by grafst** [lepture/python-livereload#267]
this:
```
> venv/bin/activate
> python3 -m pip install livereload
> livereload
```

results in this:
```
Traceback (most recent call last):
  File "/Users/stephan/git/tennn/venv/bin/livereload", line 5, in <module>
    from livereload.cli import main
  File "/Users/stephan/git/tennn/venv/lib/python3.10/site-packages/livereload/__init__.py", line 15, in <module>
    from .server import Server, shell
  File "/Users/stephan/git/tennn/venv/lib/python3.10/site-packages/livereload/server.py", line 20, in <module>
    from tornado.wsgi import WSGIContainer
  File "/Users/stephan/git/tennn/venv/lib/python3.10/site-packages/tornado/wsgi.py", line 40, in <module>
    from tornado import httputil
  File "/Users/stephan/git/tennn/venv/lib/python3.10/site-packages/tornado/httputil.py", line 106, in <module>
    class HTTPHeaders(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

**Comment by lepture** [comment]
Maybe tornado doesn't support python 3.10. Try python <= 3.9.
